### ISSUE TITLE
Accessory Tab collapses

### ISSUE THREAD

**Issue by jtrascap** [davist11/Environment-EE-Addon#1]
Added it to EE 2.5.3 and the tab collapses. Checked with inspector and got this:  

```
<div id="environment" class="accessory">
  <div class="accessorySection">
  <h5>0</h5>
  <script type="text/javascript">$("#accessoryTabs a.environment").parent().remove();</script>
</div>
<!-- accessorySection -->
```

Turned-off all other accessories and reverted to basic theme (I normally use Nerdery) and no difference. Momentarily flashes and collapses into its parent DIV.

**Comment by davist11** [comment]
I tested on 2.5.3 with both the basic theme and Nerdery as well. The accessory tab is supposed to collapse itself. Based on the JS being output, are you sure you are setting the ENV variable in your config.php?

**Comment by jtrascap** [comment]
Yep - that was it. Thanks for the help. 

Mind if I suggest something? It's a great idea but it overlaps buttons in the cp (I use a lot of shortcuts). Maybe have an an option for positioning, or to leave it as a black tab in the accessory area?

**Comment by davist11** [comment]
My only struggle was figuring out where else you could position it.

**Comment by jtrascap** [comment]
Yeah - I'm late. Sorry. 
How about injecting it immediately after div#mainWrapper and before div#sideBar?

Setting div#mainWrapper to position:relative doesn't break anything (2.5.5 & 2.6) and then use something like this on   div.environment-label:

``` css
position: absolute;
right: 23.2%;
background-color: 
rgba(000,000,000,.5);
color: #fff;
padding: 7px 17px 7px;
top: 0;
font-size: 125%;
```

so that it hangs just left of the user block on div#sideBar (I prefer a little gap, but right:23% will move nicely with the sideBar)
![movethelabel](https://f.cloud.github.com/assets/42548/429721/aac577f4-ae4f-11e2-9f9a-7ae70042a4bb.jpg)

**Comment by davist11** [comment]
I think I prefer the original placement, especially since it stays fixed on the screen.
